name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: atria_user
          POSTGRES_DB: atria_test
          POSTGRES_PASSWORD: secretpassword
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Run Tests
        env:
          TEST_DATABASE_URL: postgres://atria_user:secretpassword@localhost:5432/atria_test?sslmode=disable
        run: go test ./... -p 1 -v
